#! /bin/bash

templates=$(dirname $0)/templates

infrastructure=$1

shift

spiff merge \
  $templates/jira-template.yml \
  $templates/jira-jobs.yml \
  $templates/$infrastructure-networks.yml \
  $templates/$infrastructure-resource-pools.yml \
  $*
